language: java
jdk:
  - oraclejdk8
before_install:
 - chmod +x mvnw
after_success:
  - ./mvnw clean test jacoco:report coveralls:report
branches:
  only:
  - master
  - develop
cache:
  directories:
  - .autoconf
  - $HOME/.m2