swagger: "2.0"
info:
  description: "This is the API for the Reactive Micro Service example"
  version: "1.0.0"
  title: "Reactive Micro Services API"
  contact:
    url: "https://github.com/LearningByExample/reactive-ms-example"
host: "localhost:8080"
basePath: "/api"
tags:
- name: "location"
  description: "geo location services"
schemes:
- "http"
paths:
  /location/{address}:
    get:
      tags:
      - "location"
      summary: "get latitude, longitude, sunrise and sunset from an address parameter"
      produces:
      - "application/json"
      parameters:
      - name: "address"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/LocationResponse"
  /location:
    post:
      tags:
      - "location"
      summary: "get latitude, longitude, sunrise and sunset from an LocationRequest object"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "LocationRequest object that has an address"
        required: true
        schema:
          $ref: "#/definitions/LocationRequest"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/LocationResponse"
definitions:
  LocationRequest:
    type: "object"
    properties:
      address:
        type: "string"
  LocationResponse:
    type: "object"
    properties:
      geographicCoordinates:
        type: "object"
        properties:
          latitude:
            type: "number"
            format: "double"
          longitude:
            type: "number"
            format: "double"
      sunriseSunset:
        type: "object"
        properties:
          sunrise:
            type: "string"
            format: "date-time"
            description: "ISO 8601 UTC without summer time adjustment"
          sunset:
            type: "string"
            format: "date-time"
            description: "ISO 8601 UTC without summer time adjustment"
